import { useEffect } from "react";
import { Link } from "wouter";
import { Layout } from "@/components/Layout";
import { FileText } from "lucide-react";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display font-bold text-xl text-foreground mb-3">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  useEffect(() => {
    document.title = "Terms of Service – CalcSpark";
    const meta = document.querySelector<HTMLMetaElement>('meta[name="description"]');
    if (meta) meta.content = "CalcSpark Terms of Service. Free to use for personal and educational purposes. All calculations are informational only.";
  }, []);

  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="flex items-center gap-3 mb-2">
          <div className="h-10 w-10 bg-primary/10 rounded-xl flex items-center justify-center text-primary shrink-0">
            <FileText className="h-5 w-5" />
          </div>
          <div>
            <h1 className="font-display font-bold text-2xl sm:text-3xl text-foreground">Terms of Service</h1>
            <p className="text-xs text-muted-foreground mt-0.5">Last updated: January 2025</p>
          </div>
        </div>

        <div className="bg-primary/5 border border-primary/20 rounded-xl p-4 mb-8 mt-6">
          <p className="text-sm text-foreground font-medium">
            By using CalcSpark, you agree to these Terms of Service. Please read them carefully.
            CalcSpark is free to use for personal, educational, and non-commercial purposes.
          </p>
        </div>

        <div className="bg-card border border-border rounded-2xl p-6 sm:p-8">
          <Section title="1. Acceptance of Terms">
            <p>By accessing and using CalcSpark (&ldquo;the Site&rdquo;, &ldquo;the Service&rdquo;), you accept and agree to be bound by these Terms of Service and our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>. If you do not agree to these terms, please do not use the Service.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>CalcSpark provides a collection of free, browser-based calculators, converters, and mathematical tools (&ldquo;Tools&rdquo;). All tools run entirely in your web browser — no data is transmitted to our servers during calculations.</p>
            <p>The Service is provided free of charge and without registration. We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice.</p>
          </Section>

          <Section title="3. Acceptable Use">
            <p>You may use CalcSpark for personal, educational, and informational purposes. You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Attempt to circumvent, disable, or interfere with the Site&apos;s security features</li>
              <li>Use automated bots or scrapers to access the Service at scale</li>
              <li>Attempt to reverse-engineer or extract our source code for commercial purposes</li>
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
              <li>Reproduce or republish our content without proper attribution</li>
            </ul>
          </Section>

          <Section title="4. Informational Purpose Only">
            <p>All calculators and tools on CalcSpark are provided for <strong className="text-foreground">informational and educational purposes only</strong>. The results generated by our tools should not be used as the sole basis for:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Medical diagnoses, treatment, or health decisions</li>
              <li>Legal advice or legal decisions</li>
              <li>Financial or investment decisions</li>
              <li>Engineering or structural calculations where safety is at risk</li>
            </ul>
            <p>Always consult a qualified professional before making important decisions. See our <Link href="/disclaimer" className="text-primary hover:underline">Disclaimer</Link> for full details.</p>
          </Section>

          <Section title="5. Accuracy of Information">
            <p>While we strive to ensure all calculations are accurate and based on established formulas, CalcSpark makes no warranties or representations as to the accuracy, completeness, or reliability of any results. Mathematical tools are subject to the precision limitations of floating-point arithmetic.</p>
          </Section>

          <Section title="6. Intellectual Property">
            <p>All content on CalcSpark — including text, design, code, tool implementations, and branding — is owned by or licensed to CalcSpark and is protected by applicable intellectual property laws.</p>
            <p>You may share links to our tools freely. You may not reproduce, distribute, or create derivative works without written permission, except where permitted under applicable fair use laws.</p>
          </Section>

          <Section title="7. Third-Party Links">
            <p>CalcSpark may contain links to third-party websites (e.g., LinkedIn profiles, reference sources). We are not responsible for the content, privacy practices, or terms of those sites. Visiting them is at your own discretion.</p>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. To the fullest extent permitted by law, CalcSpark disclaims all warranties including merchantability, fitness for a particular purpose, and non-infringement.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>To the maximum extent permitted by applicable law, CalcSpark and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, even if advised of the possibility of such damages.</p>
          </Section>

          <Section title="10. Changes to Terms">
            <p>We reserve the right to update these Terms at any time. Material changes will be indicated by an updated &ldquo;Last updated&rdquo; date. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </Section>

          <Section title="11. Governing Law">
            <p>These Terms shall be governed by and construed in accordance with applicable laws. Any disputes shall be resolved in the appropriate courts of jurisdiction.</p>
          </Section>

          <Section title="12. Contact">
            <p>For any questions regarding these Terms, please contact us:</p>
            <ul className="list-none space-y-1">
              <li>Email: <a href="mailto:hello@calcspark.io" className="text-primary hover:underline">hello@calcspark.io</a></li>
              <li>Via our <Link href="/contact" className="text-primary hover:underline">Contact Page</Link></li>
            </ul>
          </Section>
        </div>
      </div>
    </Layout>
  );
}
